services:
  node-backend:
    build:
      context: ./backend-node
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./backend-node:/app
      - /app/node_modules
    env_file:
      - backend-node/.env
    environment:
      - REDIS_HOST=redis-container
    command: /bin/sh -c "pnpm run prisma:migrate && pnpm run dev"
    restart: always

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
